---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aws.my.controller
  resources:
  - vms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.my.controller
  resources:
  - vms/finalizers
  verbs:
  - update
- apiGroups:
  - aws.my.controller
  resources:
  - vms/status
  verbs:
  - get
  - patch
  - update
