# permissions for end users to edit vms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vm-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-controller
    app.kubernetes.io/part-of: vm-controller
    app.kubernetes.io/managed-by: kustomize
  name: vm-editor-role
rules:
- apiGroups:
  - aws.my.domain
  resources:
  - vms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.my.domain
  resources:
  - vms/status
  verbs:
  - get
